apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-onedev-ssh
  labels:
    tier: server
    app: ondev
spec:
  type: {{ .Values.services.ssh.spec.type }}
  ports:
    - name: ssh
      port: {{ .Values.services.ssh.spec.port }}
      targetPort: 6611
      protocol: TCP
  selector:
    tier: server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-onedev-http
  labels:
    tier: server
    app: ondev
spec:
  type: {{ .Values.services.http.spec.type }}
  ports:
    - name: http
      port: {{ .Values.services.http.spec.port }}
      targetPort: 6610
      protocol: TCP
  selector:
    tier: server
---
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    tier: database
    app: onedev
spec:
  ports:
    - port: 3306
  selector:
    tier: database
