image:
  pullPolicy: IfNotPresent
  tag: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


volumes:
  onedev:
    storageClassName: openebs-hostpath
    size: 100Gi
  mysql:
    storageClassName: openebs-hostpath
    size: 20Gi

resources:
  onedev:
    memory: 2Gi
  mysql:
    memory: 500Mi

services:
  ssh:
    spec:
      port: 22
      type: ClusterIP
  http:
    spec:
      port: 22
      type: ClusterIP